### ISSUE TITLE
Create playing functionality

### ISSUE THREAD

**Issue by j-arsenault** [ianarsenault/Pulse-Roshambo#15]
**First off -**
I'm gonna be adding the original roshambo's play code to the assets folder.

This will be so we can grab what we need from it in order to build our play functionality, and also use it as a way to come up with maybe simpler/better functionality.

**Actual Issue**
Creating the functionality to play between two players.

@TODO:
- [ ] Move meat and potatoes to Server
- [ ] Create service on client

**Comment by jaydeluca** [comment]
been patiently waiting for a jameson commit. Push it up and lets optimize this battle algorithmmmm

**Comment by j-arsenault** [comment]
**Update**
The old code has been put into the assets folder under the name -- oldPlayCode.js

Now to build our actual functionality.

**Comment by ianarsenault** [comment]
I don't really know how to go about tackling this. Should we turn the old functionality into a roshambo class to import into the landing/play component?

```js
import Form from '../assets/scripts/roshambo.js';

export default {
  data () {
      return {
        roshambo: new Roshambo()
      }
    },
}
```

Or do we just create the functions we need within that component?

**Comment by jaydeluca** [comment]
First option - lets create a class

**Comment by jaydeluca** [comment]
![giphy](https://user-images.githubusercontent.com/7630696/37810074-b335bf12-2e28-11e8-8f94-783f2818fe15.gif)
