### ISSUE TITLE
Graphing Data

### ISSUE THREAD

**Issue by ianarsenault** [ianarsenault/Pulse-Roshambo#37]
Implement a feature to graph the data on matches and or players on either player or leaderboard components.

**Use Cases:**
- overall matches played with total wins from each player
- players win loss ratio
- worst player based on `Math.random()`
- wins/losses versus certain players

Feel free to add more cases.

Suggested chart frameworks to use:
- [d3](https://d3js.org/)
- [Chart JS](http://www.chartjs.org/)
- [Chartist JS](https://gionkunz.github.io/chartist-js/)

**Comment by j-arsenault** [comment]
Another Use Case could be:

- Showing Players how many wins/losses they have vs the last certain # of players they've played?

**Comment by ianarsenault** [comment]
This is getting closed for now. V2 will reopen.
