### ISSUE TITLE
Move Battle Engine to Server

### ISSUE THREAD

**Issue by jaydeluca** [ianarsenault/Pulse-Roshambo#45]
- [x] Move battle code to server
- [x] Create service on client

**Comment by jaydeluca** [comment]
This is just about done. The leaderboard just doesn't work, but I haven't looked into whether I broke that or if it hadn't been completed yet.

I think we should try and close some of these PR's and get them merged into master, as some of these branches are getting a bit out of sync. 

I merged this one with the current state of the leaderboard branch just to avoid so many conflicts later on.

**Comment by jkys** [comment]
I finish up leaderboards today, so we can merge everything in
