### ISSUE TITLE
PI-003: Refreshing any page other than the home page results in error

### ISSUE THREAD

**Issue by j-arsenault** [ianarsenault/Pulse-Roshambo#65]
This happens when you refresh any page other than the home page:
![snip20180412_11](https://user-images.githubusercontent.com/11837811/38713234-2f3211f8-3e9e-11e8-8fba-a2a3e59471da.png)

**Comment by jaydeluca** [comment]
Note: this is likely related to the nginx server configuration, as that is an nginx error page, and the problem does not exist locally.
